
services:
  mesa-validate:
    build: 
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    ports:
      - "8501:8501"
    volumes:
      - ./predictions/:/app/predictions
      - ./sessions/:/app/sessions
    restart: unless-stopped
